# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import play_room_requests_pb2 as play__room__requests__pb2


class PlayRoomRequestsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPlay = channel.unary_unary(
                '/play_room_requests.PlayRoomRequests/StartPlay',
                request_serializer=play__room__requests__pb2.StartPlayRequest.SerializeToString,
                response_deserializer=play__room__requests__pb2.NewRoleAssignment.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/play_room_requests.PlayRoomRequests/Heartbeat',
                request_serializer=play__room__requests__pb2.StateRequest.SerializeToString,
                response_deserializer=play__room__requests__pb2.StateResponse.FromString,
                )
        self.SetAction = channel.unary_unary(
                '/play_room_requests.PlayRoomRequests/SetAction',
                request_serializer=play__room__requests__pb2.Action.SerializeToString,
                response_deserializer=play__room__requests__pb2.NewRoleAssignment.FromString,
                )


class PlayRoomRequestsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartPlay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayRoomRequestsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPlay': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPlay,
                    request_deserializer=play__room__requests__pb2.StartPlayRequest.FromString,
                    response_serializer=play__room__requests__pb2.NewRoleAssignment.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=play__room__requests__pb2.StateRequest.FromString,
                    response_serializer=play__room__requests__pb2.StateResponse.SerializeToString,
            ),
            'SetAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAction,
                    request_deserializer=play__room__requests__pb2.Action.FromString,
                    response_serializer=play__room__requests__pb2.NewRoleAssignment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'play_room_requests.PlayRoomRequests', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayRoomRequests(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPlay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/play_room_requests.PlayRoomRequests/StartPlay',
            play__room__requests__pb2.StartPlayRequest.SerializeToString,
            play__room__requests__pb2.NewRoleAssignment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/play_room_requests.PlayRoomRequests/Heartbeat',
            play__room__requests__pb2.StateRequest.SerializeToString,
            play__room__requests__pb2.StateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/play_room_requests.PlayRoomRequests/SetAction',
            play__room__requests__pb2.Action.SerializeToString,
            play__room__requests__pb2.NewRoleAssignment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
