# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_room_requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='play_room_requests.proto',
  package='play_room_requests',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18play_room_requests.proto\x12\x12play_room_requests\"\x1c\n\x0cStateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"M\n\x06\x41\x63tion\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x08\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0b\n\x03who\x18\x05 \x01(\t\"\xca\x03\n\rStateResponse\x12\x15\n\rgame_finished\x18\x01 \x01(\x08\x12\x12\n\nday_number\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\x08\x12;\n\x05\x61live\x18\x04 \x03(\x0b\x32,.play_room_requests.StateResponse.AliveEntry\x12?\n\x07\x61\x63tions\x18\x05 \x03(\x0b\x32..play_room_requests.StateResponse.ActionsEntry\x12;\n\x05roles\x18\x06 \x03(\x0b\x32,.play_room_requests.StateResponse.RolesEntry\x12\x1c\n\x14time_till_next_event\x18\x07 \x01(\x01\x1a,\n\nAliveEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x1aJ\n\x0c\x41\x63tionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.play_room_requests.Action:\x02\x38\x01\x1a,\n\nRolesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x10StartPlayRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x11NewRoleAssignment\x12\x0c\n\x04role\x18\x01 \x01(\t2\x94\x02\n\x10PlayRoomRequests\x12Z\n\tStartPlay\x12$.play_room_requests.StartPlayRequest\x1a%.play_room_requests.NewRoleAssignment\"\x00\x12R\n\tHeartbeat\x12 .play_room_requests.StateRequest\x1a!.play_room_requests.StateResponse\"\x00\x12P\n\tSetAction\x12\x1a.play_room_requests.Action\x1a%.play_room_requests.NewRoleAssignment\"\x00\x62\x06proto3'
)




_STATEREQUEST = _descriptor.Descriptor(
  name='StateRequest',
  full_name='play_room_requests.StateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='play_room_requests.StateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=76,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='play_room_requests.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='play_room_requests.Action.day', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='play_room_requests.Action.state', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='play_room_requests.Action.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='play_room_requests.Action.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='who', full_name='play_room_requests.Action.who', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=155,
)


_STATERESPONSE_ALIVEENTRY = _descriptor.Descriptor(
  name='AliveEntry',
  full_name='play_room_requests.StateResponse.AliveEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='play_room_requests.StateResponse.AliveEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='play_room_requests.StateResponse.AliveEntry.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=494,
)

_STATERESPONSE_ACTIONSENTRY = _descriptor.Descriptor(
  name='ActionsEntry',
  full_name='play_room_requests.StateResponse.ActionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='play_room_requests.StateResponse.ActionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='play_room_requests.StateResponse.ActionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=570,
)

_STATERESPONSE_ROLESENTRY = _descriptor.Descriptor(
  name='RolesEntry',
  full_name='play_room_requests.StateResponse.RolesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='play_room_requests.StateResponse.RolesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='play_room_requests.StateResponse.RolesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=616,
)

_STATERESPONSE = _descriptor.Descriptor(
  name='StateResponse',
  full_name='play_room_requests.StateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_finished', full_name='play_room_requests.StateResponse.game_finished', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='day_number', full_name='play_room_requests.StateResponse.day_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='play_room_requests.StateResponse.state', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alive', full_name='play_room_requests.StateResponse.alive', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='play_room_requests.StateResponse.actions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roles', full_name='play_room_requests.StateResponse.roles', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_till_next_event', full_name='play_room_requests.StateResponse.time_till_next_event', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATERESPONSE_ALIVEENTRY, _STATERESPONSE_ACTIONSENTRY, _STATERESPONSE_ROLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=616,
)


_STARTPLAYREQUEST = _descriptor.Descriptor(
  name='StartPlayRequest',
  full_name='play_room_requests.StartPlayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='play_room_requests.StartPlayRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=650,
)


_NEWROLEASSIGNMENT = _descriptor.Descriptor(
  name='NewRoleAssignment',
  full_name='play_room_requests.NewRoleAssignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='role', full_name='play_room_requests.NewRoleAssignment.role', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=685,
)

_STATERESPONSE_ALIVEENTRY.containing_type = _STATERESPONSE
_STATERESPONSE_ACTIONSENTRY.fields_by_name['value'].message_type = _ACTION
_STATERESPONSE_ACTIONSENTRY.containing_type = _STATERESPONSE
_STATERESPONSE_ROLESENTRY.containing_type = _STATERESPONSE
_STATERESPONSE.fields_by_name['alive'].message_type = _STATERESPONSE_ALIVEENTRY
_STATERESPONSE.fields_by_name['actions'].message_type = _STATERESPONSE_ACTIONSENTRY
_STATERESPONSE.fields_by_name['roles'].message_type = _STATERESPONSE_ROLESENTRY
DESCRIPTOR.message_types_by_name['StateRequest'] = _STATEREQUEST
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['StateResponse'] = _STATERESPONSE
DESCRIPTOR.message_types_by_name['StartPlayRequest'] = _STARTPLAYREQUEST
DESCRIPTOR.message_types_by_name['NewRoleAssignment'] = _NEWROLEASSIGNMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateRequest = _reflection.GeneratedProtocolMessageType('StateRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEREQUEST,
  '__module__' : 'play_room_requests_pb2'
  # @@protoc_insertion_point(class_scope:play_room_requests.StateRequest)
  })
_sym_db.RegisterMessage(StateRequest)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'play_room_requests_pb2'
  # @@protoc_insertion_point(class_scope:play_room_requests.Action)
  })
_sym_db.RegisterMessage(Action)

StateResponse = _reflection.GeneratedProtocolMessageType('StateResponse', (_message.Message,), {

  'AliveEntry' : _reflection.GeneratedProtocolMessageType('AliveEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATERESPONSE_ALIVEENTRY,
    '__module__' : 'play_room_requests_pb2'
    # @@protoc_insertion_point(class_scope:play_room_requests.StateResponse.AliveEntry)
    })
  ,

  'ActionsEntry' : _reflection.GeneratedProtocolMessageType('ActionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATERESPONSE_ACTIONSENTRY,
    '__module__' : 'play_room_requests_pb2'
    # @@protoc_insertion_point(class_scope:play_room_requests.StateResponse.ActionsEntry)
    })
  ,

  'RolesEntry' : _reflection.GeneratedProtocolMessageType('RolesEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATERESPONSE_ROLESENTRY,
    '__module__' : 'play_room_requests_pb2'
    # @@protoc_insertion_point(class_scope:play_room_requests.StateResponse.RolesEntry)
    })
  ,
  'DESCRIPTOR' : _STATERESPONSE,
  '__module__' : 'play_room_requests_pb2'
  # @@protoc_insertion_point(class_scope:play_room_requests.StateResponse)
  })
_sym_db.RegisterMessage(StateResponse)
_sym_db.RegisterMessage(StateResponse.AliveEntry)
_sym_db.RegisterMessage(StateResponse.ActionsEntry)
_sym_db.RegisterMessage(StateResponse.RolesEntry)

StartPlayRequest = _reflection.GeneratedProtocolMessageType('StartPlayRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTPLAYREQUEST,
  '__module__' : 'play_room_requests_pb2'
  # @@protoc_insertion_point(class_scope:play_room_requests.StartPlayRequest)
  })
_sym_db.RegisterMessage(StartPlayRequest)

NewRoleAssignment = _reflection.GeneratedProtocolMessageType('NewRoleAssignment', (_message.Message,), {
  'DESCRIPTOR' : _NEWROLEASSIGNMENT,
  '__module__' : 'play_room_requests_pb2'
  # @@protoc_insertion_point(class_scope:play_room_requests.NewRoleAssignment)
  })
_sym_db.RegisterMessage(NewRoleAssignment)


_STATERESPONSE_ALIVEENTRY._options = None
_STATERESPONSE_ACTIONSENTRY._options = None
_STATERESPONSE_ROLESENTRY._options = None

_PLAYROOMREQUESTS = _descriptor.ServiceDescriptor(
  name='PlayRoomRequests',
  full_name='play_room_requests.PlayRoomRequests',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=688,
  serialized_end=964,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartPlay',
    full_name='play_room_requests.PlayRoomRequests.StartPlay',
    index=0,
    containing_service=None,
    input_type=_STARTPLAYREQUEST,
    output_type=_NEWROLEASSIGNMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='play_room_requests.PlayRoomRequests.Heartbeat',
    index=1,
    containing_service=None,
    input_type=_STATEREQUEST,
    output_type=_STATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetAction',
    full_name='play_room_requests.PlayRoomRequests.SetAction',
    index=2,
    containing_service=None,
    input_type=_ACTION,
    output_type=_NEWROLEASSIGNMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYROOMREQUESTS)

DESCRIPTOR.services_by_name['PlayRoomRequests'] = _PLAYROOMREQUESTS

# @@protoc_insertion_point(module_scope)
